---
name: Docker
on:
  push:
    branches:
      - master
    paths:
      - 'docker/**'
      - '.github/workflows/docker.yml'
      - '.github/workflows/_sbom-benchmark.yml'
  pull_request:
    paths:
      - 'docker/**'
      - '.github/workflows/docker.yml'
      - '.github/workflows/_sbom-benchmark.yml'

jobs:
  benchmark:
    uses: ./.github/workflows/_sbom-benchmark.yml
    with:
      name: container
      target_type: docker
      target_path: nginx-test
      setup_commands: |
        cd docker && docker build . -t nginx-test
      sbomify_input: nginx-test
      sbomify_input_type: docker_image
      baseline_command: |
        docker run --rm nginx-test dpkg-query -W -f='${binary:Package} ${Version}\n' | sort
      title: Docker (nginx + vim) Benchmark
