---
name: Python
on:
  push:
    branches:
      - master
    paths:
      - 'python/**'
      - '.github/workflows/python.yml'
      - '.github/workflows/_sbom-benchmark.yml'
  pull_request:
    paths:
      - 'python/**'
      - '.github/workflows/python.yml'
      - '.github/workflows/_sbom-benchmark.yml'

jobs:
  benchmark:
    uses: ./.github/workflows/_sbom-benchmark.yml
    with:
      name: python
      target_type: filesystem
      target_path: python/requirements.txt
      sbomify_input: python/requirements.txt
      sbomify_input_type: lock_file
      extra_tools: cyclonedx-python,sbom4python
      title: Python (Django) Benchmark
