---
name: Rust
on:
  push:
    branches:
      - master
    paths:
      - 'rust/**'
      - '.github/workflows/rust.yml'
      - '.github/workflows/_sbom-benchmark.yml'
  pull_request:
    paths:
      - 'rust/**'
      - '.github/workflows/rust.yml'
      - '.github/workflows/_sbom-benchmark.yml'

jobs:
  benchmark:
    uses: ./.github/workflows/_sbom-benchmark.yml
    with:
      name: rust
      target_type: filesystem
      target_path: ./target-repo
      setup_commands: |
        git clone --depth 1 --branch 0.24.5 https://github.com/cloudflare/quiche.git ./target-repo
      sbomify_input: ./target-repo/Cargo.lock
      sbomify_input_type: lock_file
      title: Rust (Cloudflare quiche 0.24.5) Benchmark
